[ai]
ai_similarity_enabled = false
ai_similarity_keywords = ""

[settings]
allow_nsfw = false
theme = "light"
times_to_run = 1
opacity = 1.0
storymode = false
storymodemethod = 1
storymode_max_length = 1000
resolution_w = 1080
resolution_h = 1920
zoom = 1.0
channel_name = "IndianWorkplace"

[settings.background]
background_video = "minecraft"
background_audio = "lofi"
background_audio_volume = 0.15
enable_extra_audio = false
background_thumbnail = false
background_thumbnail_font_family = "arial"
background_thumbnail_font_size = 96
background_thumbnail_font_color = "255,255,255"

[settings.tts]
voice_choice = "streamlabspolly"
random_voice = false
elevenlabs_voice_name = "Bella"
elevenlabs_api_key = "sk_18e35247152a344b5e6cbf1632e5fe4c82e813054d3bc1ee"
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_001"
tiktok_sessionid = ""
python_voice = "1"
py_voice_num = "2"
silence_duration = 0.3
no_emojis = false

[reddit.creds]
client_id = "si_jhrlK3ngZR-dLzGj15g"
client_secret = "EY1nsNUqjeOJgXWyxas_Lhdynxqo3Q"
username = "Harrrdik18"
password = "9893192894"
2fa = false

[reddit.thread]
random = false
subreddit = "IndianWorkplace"
post_id = "1jsn7f7"
max_comment_length = 500
min_comment_length = 1
post_lang = ""
min_comments = 20
